language: ruby
rvm:
- 2.4.1
before_install:
- gem install bundler
before_script:
- chmod +x ./script/cibuild
script: "./script/cibuild"
before_deploy:
- openssl aes-256-cbc -K $encrypted_3bd2740ed5c2_key -iv $encrypted_3bd2740ed5c2_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete --quiet $TRAVIS_BUILD_DIR/_site/ mattf@hack.osu.edu:/usr/share/nginx/ohio/
  on:
    branch: master
addons:
  ssh_known_hosts: hack.osu.edu
sudo: false
cache: bundler
